### ISSUE TITLE
Multi-day tasks?

### ISSUE THREAD

**Issue by Kartones** [Kartones/flask-calendar#24]
Just an idea, needs definition

**Comment by riccrastle** [comment]
I would also like to +1 for tasks that span days. Potentially even a reoccurring span such as something that is only happens mon-fri, rather than 5 weekly tasks that are copy-pastes and have be cancelled individually. I think many recurrences would also benefit from an optional end date.

**Comment by Kartones** [comment]
Basic implementation provided by https://github.com/Kartones/flask-calendar/pull/37

**Comment by foxyblue** [comment]
I quite like the basic implementation, for example a conference which spans 3 days might have a different line-up on each day. The current implementation allows you to specify different descriptions on each day.

**Comment by Kartones** [comment]
Closing this issue, as the implementation from https://github.com/Kartones/flask-calendar/pull/37 is good enough.
