### ISSUE TITLE
Forbidden You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

### ISSUE THREAD

**Issue by kristoferus75** [Kartones/flask-calendar#30]
Hi !

start the server:

python -m flask_calendar.app

I already add a user and password but after login i get :

Forbidden You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.

http://192.168.1.1:5000/27/

the default_calendar="27"

Thanks !

kind regrads

kristoferus75

**Comment by Kartones** [comment]
Hi kristoferus75,

It looks as if you've setup most things but that the calendar file is not accessible, present but not readable by Flask.

I've done the following setup with the github repo:
```
# file data/27.json
{
    "tasks": {
        "normal": {},
        "repetition": [],
        "hidden_repetition": {}
    },
    "users": [
      "another_username"
    ],
    "name": "27"
}

# file users/users.json:
{
    "a_username": {
        "username": "a_username",
        "password": "5db0240249f03a49d95dbe624ef856293b8c1fae0703c0b725c013f585778074",
        "default_calendar": "sample",
        "ics_key": "an_ics_key"
    },
    "another_username": {
        "username": "another_username",
        "password": "5db0240249f03a49d95dbe624ef856293b8c1fae0703c0b725c013f585778074",
        "default_calendar": "27",
        "ics_key": "an_ics_key"
    }
}
```
(`another_username` has same password as `a_username`)
And I can login an automatically get redirected to `http://0.0.0.0:5000/27/` (the index of that user) and can see an empty calendar... so my guess is that maybe python doesn't has read/write access to the `data` subfolder (or wherever you've moved the calendar data jsons).

Check that and let me know

**Comment by Kartones** [comment]
closing due to lack of feedback and not being able to reproduce locally
