### ISSUE TITLE
calendar to filter data

### ISSUE THREAD

**Issue by bbartling** [Kartones/flask-calendar#36]
Hello,

I apologize if creating an issue is not the correct path for researching... But I was curious if I could use this to filter data?

For example, I have an app that can create some charts where the user first imports a CSV file containing numerical time series data via the browser. And a cool feature would be to able to filter the dataset based on some calendar dates selectable from the front end.

For example something bare bones the app user via the browser clicks a button to browse for a CSV file on this route:

```
@app.route('/transform', methods=["POST"])
def transform_view():

    f = request.files['data_file']
    filename = secure_filename(f.filename)
    f.save(filename)

    df = pd.read_csv(filename, index_col='Date', parse_dates=True)
```

And then could I use a calendar feature to filter the data? The idea that I have in mind would like a generic weekly calendar where the person could select specific time periods, like every week 1PM-5PM filter out all other data...

Hopefully this makes sense! Or would you have any other tips for other calendar features creations for Flask?

Thank you!
Ben

**Comment by Kartones** [comment]
Hi @bbartling,

No problem at all on asking here, but I'm sad to inform you that this project won't be of use to filter data as you want, it almost doesn't has any filtering at all (just shows a full calendar month), no date filters or anything similar...

It is meant to be a minimalistic replacement for Google Calendar (and personally to me it does replace it), so I also don't have any plan of supporting complex views and/or filters.

Sorry and good luck on your search!
